*** Settings ***
Library     SeleniumLibrary    timeout=30
Library     ScreenCapLibrary
Library     OperatingSystem
Resource    ../common/common_keywords.resource
Resource    ../pages/cart/cart_keywords.resource
Resource    ../pages/detail_product/detail_product_keywords.resource
Resource    ../pages/home/home_keywords.resource
Resource    ../pages/login/login_keywords.resource
Resource    ../pages/place_order/place_order_keywords.resource
